server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:9090/realms/microservices-sb2-realm/protocol/openid-connect/auth
            userinfo-uri: http://localhost:9090/realms/microservices-sb2-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
            token-uri: http://localhost:9090/realms/microservices-sb2-realm/protocol/openid-connect/token
        registration:
          microservices-sb2-client:
            provider: keycloak
            client-id: microservices-sb2-client
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${BASE_URL:http://localhost:8080}/login/oauth2/code/microservices-sb2-client
  application:
    zipkin: http://localhost:9411
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: bike-service
          uri: lb://bike-service
          predicates:
            - Path=/bike/**
        - id: car-service
          uri: lb://car-service
          predicates:
            - Path=/car/**